package screens.HoaDon;

import javax.swing.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.sql.Timestamp;
import DAO.HoaDonDAO;
import DAO.SanPhamDAO;
import DTO.hoaDonDTO;
import DTO.sanPhamDTO;

/**
 *
 * @author [Your Name]
 */
public class xoaHoaDonPanel extends JFrame {

    private HoaDonDAO hoaDonDAO;
    private SanPhamDAO sanPhamDAO;
    private SimpleDateFormat dateFormat;
    private hoaDonDTO hoaDon;

    /**
     * Creates new form xoaHoaDonPanel
     */
    public xoaHoaDonPanel(hoaDonDTO hoaDon) {
        if (hoaDon == null) {
            JOptionPane.showMessageDialog(null, "Hóa đơn không hợp lệ!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }
        this.hoaDon = hoaDon;
        hoaDonDAO = new HoaDonDAO();
        sanPhamDAO = new SanPhamDAO();
        dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        setVisible(false); // Ẩn JFrame, không hiển thị giao diện
        confirmAndDelete(); // Gọi phương thức xóa ngay lập tức
    }

    /**
     * Phương thức hiển thị hộp thoại xác nhận và thực hiện xóa
     */
    private void confirmAndDelete() {
        try {
            int confirm = JOptionPane.showConfirmDialog(null,
                    "Bạn có chắc chắn muốn xóa hóa đơn " + hoaDon.getMaHoaDon() + " không?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                // Lấy thông tin sản phẩm để cập nhật số lượng tồn kho
                sanPhamDTO sp = sanPhamDAO.getSanPhamByMa(hoaDon.getMaSanPham());
                if (sp != null) {
                    // Tăng số lượng tồn kho vì hóa đơn bị xóa
                    int soLuongXoa = hoaDon.getSoLuong();
                    int newSoLuongTonKho = sp.getSoLuongTonKho() + soLuongXoa;
                    sp.setSoLuongTonKho(newSoLuongTonKho);
                    boolean updateSuccess = sanPhamDAO.updateSanPham(sp);
                    if (!updateSuccess) {
                        throw new RuntimeException("Cập nhật số lượng tồn kho thất bại!");
                    }
                }

                // Xóa hóa đơn
                boolean success = hoaDonDAO.deleteHoaDon(hoaDon.getMaHoaDon());
                if (success) {
                    JOptionPane.showMessageDialog(null, "Xóa hóa đơn thành công!", "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Không tìm thấy hóa đơn " + hoaDon.getMaHoaDon() + " trong cơ sở dữ liệu!", "Lỗi",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (RuntimeException ex) {
            JOptionPane.showMessageDialog(null, "Lỗi khi xóa hóa đơn: " + ex.getMessage(), "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            dispose(); // Đóng JFrame
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xóa Hóa Đơn");

        jPanel1.setBackground(new java.awt.Color(107, 163, 190));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bảng xóa hóa đơn"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mã hóa đơn");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Mã sản phẩm");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Tên sản phẩm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Kích cỡ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel5.setText("Màu sắc");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setText("Số lượng");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setText("Mã khách hàng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel8.setText("Tên khách hàng");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel9.setText("Đơn giá");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel10.setText("Thành tiền");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel11.setText("Hình thức TT");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jLabel12.setText("Thời gian");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel13.setText("Trạng thái");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jTextField1.setText(hoaDon.getMaHoaDon());
        jTextField1.setEditable(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 220, -1));

        jTextField2.setText(hoaDon.getMaSanPham());
        jTextField2.setEditable(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 220, -1));

        jTextField3.setText(hoaDon.getTenSanPham());
        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, -1));

        jTextField4.setText(hoaDon.getKichCo());
        jTextField4.setEditable(false);
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, -1));

        jTextField5.setText(hoaDon.getMauSac());
        jTextField5.setEditable(false);
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, -1));

        jTextField6.setText(String.valueOf(hoaDon.getSoLuong()));
        jTextField6.setEditable(false);
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, -1));

        jTextField7.setText(hoaDon.getMaKhachHang());
        jTextField7.setEditable(false);
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 220, -1));

        jTextField8.setText(hoaDon.getTenKhachHang());
        jTextField8.setEditable(false);
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 220, -1));

        jTextField9.setText(String.valueOf(hoaDon.getDonGia()));
        jTextField9.setEditable(false);
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 220, -1));

        jTextField10.setText(String.valueOf(hoaDon.getThanhTien()));
        jTextField10.setEditable(false);
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 220, -1));

        jTextField11.setText(hoaDon.getHinhThucThanhToan());
        jTextField11.setEditable(false);
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 220, -1));

        String thoiGianStr = hoaDon.getThoiGian() != null ? dateFormat.format(hoaDon.getThoiGian()) : "";
        jTextField12.setText(thoiGianStr);
        jTextField12.setEditable(false);
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 220, -1));

        jTextField13.setText(hoaDon.getTrangThai());
        jTextField13.setEditable(false);
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 220, -1));

        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, -1, -1));

        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Không sử dụng vì đã xử lý trong confirmAndDelete()
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Không sử dụng vì đã xử lý trong confirmAndDelete()
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xoaHoaDonPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Tạo một hoaDonDTO mẫu để kiểm tra
                hoaDonDTO sampleHoaDon = new hoaDonDTO();
                sampleHoaDon.setMaHoaDon("HD001");
                sampleHoaDon.setMaSanPham("SP001");
                sampleHoaDon.setTenSanPham("Sản phẩm mẫu");
                sampleHoaDon.setKichCo("M");
                sampleHoaDon.setMauSac("Xanh");
                sampleHoaDon.setSoLuong(2);
                sampleHoaDon.setMaKhachHang("KH001");
                sampleHoaDon.setTenKhachHang("Nguyễn Văn A");
                sampleHoaDon.setDonGia(100000);
                sampleHoaDon.setThanhTien(200000);
                sampleHoaDon.setHinhThucThanhToan("Tiền mặt");
                sampleHoaDon.setThoiGian(new Timestamp(System.currentTimeMillis()));
                sampleHoaDon.setTrangThai("Đã thanh toán");
                new xoaHoaDonPanel(sampleHoaDon);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    // End of variables declaration                   
}