/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens.SanPham;

/**
 *
 * @author nson9
 */
public class themsanpham extends javax.swing.JFrame {

    /**
     * Creates new form themsanpham
     */
    public themsanpham() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel24 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel24.setBackground(new java.awt.Color(107, 163, 190));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bảng thêm"));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Mã Sp");
        jPanel24.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 37, -1));

        jLabel23.setText("Màu sắc");
        jPanel24.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 51, -1));

        jLabel25.setText("Tên Sp");
        jPanel24.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 37, 26));

        jLabel26.setText("Trạng thái");
        jPanel24.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 54, -1));
        jPanel24.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 220, -1));
        jPanel24.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 220, -1));
        jPanel24.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 220, -1));
        jPanel24.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 220, -1));
        jPanel24.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 220, -1));
        jPanel24.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 240, -1));

        jButton38.setText("Hủy");
        jPanel24.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        jButton39.setText("Thêm");
        jPanel24.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));
        jPanel24.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, -1));

        jLabel1.setText("Kích cỡ");
        jPanel24.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 62, -1));

        jLabel2.setText("Mã NCC");
        jPanel24.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel3.setText("Loại Sp");
        jPanel24.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel4.setText("Số lượng");
        jPanel24.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel5.setText("Đơn giá");
        jPanel24.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, 20));

        jLabel6.setText("Hình ảnh");
        jPanel24.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));
        jPanel24.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 240, -1));
        jPanel24.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 240, -1));
        jPanel24.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, 854, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themsanpham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themsanpham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
