/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screens.NhapHang;

import javax.swing.UIManager;
import javax.swing.JOptionPane;
import DAO.SanPhamDAO;
import DAO.PhieuNhapDAO;
import DTO.PhieuNhapDTO;
import DTO.sanPhamDTO;
import java.util.Date;
import java.util.List;
import DAO.NhaCungCapDAO;
import DAO.NhapHangDAO;
import DTO.nhapHangDTO;
import DTO.hoaDonDTO;
import BUS.HoaDonBUS;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.util.stream.Collectors;
import DAO.NhaCungCap_SanPhamDAO;
import DTO.NhaCungCap_SanPhamDTO;
import BUS.NhapHangBUS;
import BUS.SanPhamBUS;
import BUS.NhaCungCapBUS;
import screens.TrangChu.trangchu;
import screens.TrangChu.AppColors;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.table.JTableHeader;

/**
 *
 * @author nson9
 */
public class nhaphang extends javax.swing.JPanel {

        private javax.swing.JLabel lblMaNCC;
        private javax.swing.JLabel lblTenNCC;

        private NhapHangBUS nhapHangBUS;
        private SanPhamBUS sanPhamBUS;
        private NhaCungCapBUS nhaCungCapBUS;
        private trangchu mainFrame;

        // Thêm biến giao diện tìm kiếm
        private javax.swing.JComboBox<String> cbSearchType;
        private javax.swing.JTextField txtSearchValue;
        private javax.swing.JButton btnSearch;
        private javax.swing.JButton btnOpenSmartImport;

        private javax.swing.JLabel lblTongTienPhieuNhap;
        private javax.swing.JTextField txtTongTienPhieuNhap;

        /**
         * Creates new form phieunhap
         */
        public nhaphang() {
                this(null);
        }

        public nhaphang(trangchu mainFrame) {
                this.mainFrame = mainFrame;
                nhapHangBUS = new NhapHangBUS();
                sanPhamBUS = new SanPhamBUS();
                nhaCungCapBUS = new NhaCungCapBUS();
                initComponents();
                populateComboBoxes();
                loadImportTable();
                setupAmountCalculation();
        }

        public javax.swing.JPanel getNhapHangPanel() {
                return containerPanel;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                // Khởi tạo các panel chính
                containerPanel = new javax.swing.JPanel();
                containerPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
                containerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                containerPanel.setBackground(AppColors.NEW_MAIN_BG_COLOR);

                jPanel1 = new javax.swing.JPanel();
                pnlHeader = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                pnlContent = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel7 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                lblNhaCungCap = new javax.swing.JTextField();
                cbMaNCC = new javax.swing.JComboBox<>();
                cbTenNCC = new javax.swing.JComboBox<>();
                lblNCC = new javax.swing.JTextField();
                pnlBoxSanPhamSoLuong = new javax.swing.JPanel();
                cbMaSanPham = new javax.swing.JComboBox<>();
                cbHinhThucThanhToan = new javax.swing.JComboBox<>();
                jTextField7 = new javax.swing.JTextField();
                lblLoaiSanPham = new javax.swing.JLabel();
                lblMaSanPham = new javax.swing.JLabel();
                lblTenSanPham = new javax.swing.JLabel();
                lblMauSac = new javax.swing.JLabel();
                lblKichThuoc = new javax.swing.JLabel();
                lblSoLuong = new javax.swing.JLabel();
                lblDonGia = new javax.swing.JLabel();
                lblHinhThucThanhToan = new javax.swing.JLabel();
                textTenSanPham = new javax.swing.JTextField();
                txtMauSac = new javax.swing.JTextField();
                txtKichThuoc = new javax.swing.JTextField();
                textSoLuong = new javax.swing.JTextField();
                jPanel9 = new javax.swing.JPanel();
                lblThanhTien = new javax.swing.JTextField();
                textThanhTien = new javax.swing.JTextField();
                jButton15 = new javax.swing.JButton();
                jButton18 = new javax.swing.JButton();
                jButton16 = new javax.swing.JButton();
                jButton17 = new javax.swing.JButton();
                btnOpenSmartImport = new javax.swing.JButton();

                lblTongTienPhieuNhap = new javax.swing.JLabel();
                txtTongTienPhieuNhap = new javax.swing.JTextField();

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 390, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 300, Short.MAX_VALUE));

                pnlHeader.setBackground(AppColors.NEW_HEADER_PANEL_BG_COLOR);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setText("QUẢN LÝ NHẬP HÀNG");
                jLabel1.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                btnOpenSmartImport.setText("Trợ Lý Nhập Hàng");
                btnOpenSmartImport.setBackground(AppColors.NEW_DEFAULT_BUTTON_COLOR);
                btnOpenSmartImport.setForeground(Color.WHITE);
                btnOpenSmartImport.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                btnOpenSmartImport.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnOpenSmartImportActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
                pnlHeader.setLayout(pnlHeaderLayout);
                pnlHeaderLayout.setHorizontalGroup(
                                pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                pnlHeaderLayout.createSequentialGroup()
                                                                                .addContainerGap(422, Short.MAX_VALUE)
                                                                                .addComponent(jLabel1)
                                                                                .addGap(180, 180, 180)
                                                                                .addComponent(btnOpenSmartImport, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(40, 40, 40)));
                pnlHeaderLayout.setVerticalGroup(
                                pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlHeaderLayout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(btnOpenSmartImport, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(14, Short.MAX_VALUE)));

                containerPanel.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

                pnlContent.setBackground(AppColors.NEW_MAIN_BG_COLOR);

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null }
                                },
                                new String[] {
                                                "STT", "Ma PN", "Mã NCC", "Mã SP", "Tên SP", "Màu sắc",
                                                "Kích thước", "Số Lượng",
                                                "Đơn giá", "Thành tiền", "Hình thức thanh toán", "Trạng thái"
                                }) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false; // Không cho phép chỉnh sửa trực tiếp trên bảng
                    }
                });
                jTable1.setShowGrid(true);
                jTable1.setBackground(Color.WHITE);
                jTable1.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                jTable1.setGridColor(AppColors.NEW_BORDER_LINES_COLOR);
                JTableHeader tableHeader = jTable1.getTableHeader();
                tableHeader.setBackground(AppColors.NEW_HEADER_PANEL_BG_COLOR);
                tableHeader.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                tableHeader.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                jScrollPane1.setViewportView(jTable1);

                jPanel7.setBackground(AppColors.NEW_MAIN_BG_COLOR);
                javax.swing.border.Border lineBorder7 = javax.swing.BorderFactory.createLineBorder(AppColors.NEW_HEADER_PANEL_BG_COLOR);
                jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(lineBorder7, "Đặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12), AppColors.NEW_MAIN_TEXT_COLOR));
                jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel5.setBackground(AppColors.NEW_MAIN_BG_COLOR);
                javax.swing.border.Border lineBorder5 = javax.swing.BorderFactory.createLineBorder(AppColors.NEW_HEADER_PANEL_BG_COLOR);
                jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(lineBorder5, "Nhà cung cấp", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12), AppColors.NEW_MAIN_TEXT_COLOR));

                lblNhaCungCap.setText("Chọn nhà cung cấp ");
                lblNhaCungCap.setEditable(false);
                lblNhaCungCap.setFocusable(false);
                lblNhaCungCap.setBackground(AppColors.NEW_MAIN_BG_COLOR);
                lblNhaCungCap.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblNhaCungCap.setBorder(BorderFactory.createEmptyBorder(2,5,2,5));

                lblMaNCC = new javax.swing.JLabel("Mã NCC");
                lblMaNCC.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblTenNCC = new javax.swing.JLabel("Tên NCC");
                lblTenNCC.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                cbMaNCC = new javax.swing.JComboBox<>();
                cbMaNCC.setBackground(Color.WHITE);
                cbMaNCC.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                cbTenNCC = new javax.swing.JComboBox<>();
                cbTenNCC.setBackground(Color.WHITE);
                cbTenNCC.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                                                .addComponent(lblMaNCC)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(cbMaNCC, 0, 180,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                                                .addComponent(lblTenNCC)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(cbTenNCC, 0, 180,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap()));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblMaNCC)
                                                                                .addComponent(cbMaNCC,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblTenNCC)
                                                                                .addComponent(cbTenNCC,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));

                jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 320, 120));

                pnlBoxSanPhamSoLuong.setBackground(AppColors.NEW_MAIN_BG_COLOR);
                javax.swing.border.Border lineBorderSP = javax.swing.BorderFactory.createLineBorder(AppColors.NEW_HEADER_PANEL_BG_COLOR);
                pnlBoxSanPhamSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder(lineBorderSP, "Sản phẩm & Số lượng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12), AppColors.NEW_MAIN_TEXT_COLOR));

                cbMaSanPham.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
                cbMaSanPham.setBackground(Color.WHITE);
                cbMaSanPham.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                lblMaSanPham.setText("Mã Sản Phẩm");
                lblMaSanPham.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblTenSanPham.setText("Tên Sản Phẩm");
                lblTenSanPham.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblMauSac.setText("Màu Sắc");
                lblMauSac.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblKichThuoc.setText("Kích Thước");
                lblKichThuoc.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblSoLuong.setText("Số Lượng");
                lblSoLuong.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblDonGia.setText("Đơn Giá");
                lblDonGia.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblHinhThucThanhToan.setText("Hình Thức Thanh Toán");
                lblHinhThucThanhToan.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                cbHinhThucThanhToan.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Tiền Mặt", "Chuyển Khoản", "Thẻ" }));
                cbHinhThucThanhToan.setBackground(Color.WHITE);
                cbHinhThucThanhToan.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                textTenSanPham.setBackground(Color.WHITE);
                textTenSanPham.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                textTenSanPham.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));

                txtMauSac.setBackground(Color.WHITE);
                txtMauSac.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                txtMauSac.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));

                txtKichThuoc.setBackground(Color.WHITE);
                txtKichThuoc.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                txtKichThuoc.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                txtKichThuoc.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtKichThuocActionPerformed(evt);
                        }
                });

                textSoLuong.setBackground(Color.WHITE);
                textSoLuong.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                textSoLuong.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                textSoLuong.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textSoLuongActionPerformed(evt);
                        }
                });

                // Non-editable jTextField7 (Đơn giá)
                jTextField7.setEditable(false);
                jTextField7.setBackground(Color.WHITE);
                jTextField7.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                jTextField7.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                javax.swing.GroupLayout pnlBoxSanPhamSoLuongLayout = new javax.swing.GroupLayout(pnlBoxSanPhamSoLuong);
                pnlBoxSanPhamSoLuong.setLayout(pnlBoxSanPhamSoLuongLayout);
                pnlBoxSanPhamSoLuongLayout.setHorizontalGroup(
                                pnlBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(lblMaSanPham)
                                                                                .addComponent(lblTenSanPham)
                                                                                .addComponent(lblMauSac)
                                                                                .addComponent(lblKichThuoc)
                                                                                .addComponent(lblSoLuong)
                                                                                .addComponent(lblDonGia)
                                                                                .addComponent(lblHinhThucThanhToan))
                                                                .addGap(50, 50, 50)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(cbMaSanPham, 0, 172,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jTextField7)
                                                                                .addComponent(textTenSanPham)
                                                                                .addComponent(txtMauSac)
                                                                                .addComponent(txtKichThuoc)
                                                                                .addComponent(textSoLuong)
                                                                                .addComponent(cbHinhThucThanhToan, 0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(22, Short.MAX_VALUE)));
                pnlBoxSanPhamSoLuongLayout.setVerticalGroup(
                                pnlBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(cbMaSanPham,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblMaSanPham))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(textTenSanPham,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblTenSanPham))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtMauSac,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblMauSac))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtKichThuoc,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblKichThuoc))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                18,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(textSoLuong,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblSoLuong))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jTextField7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblDonGia))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(cbHinhThucThanhToan,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblHinhThucThanhToan))
                                                                .addGap(9, 9, 9)));

                jPanel7.add(pnlBoxSanPhamSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 440, 280));

                jPanel9.setBackground(AppColors.NEW_MAIN_BG_COLOR);
                javax.swing.border.Border lineBorder9 = javax.swing.BorderFactory.createLineBorder(AppColors.NEW_HEADER_PANEL_BG_COLOR);
                jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(lineBorder9, "Chi Phí", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12), AppColors.NEW_MAIN_TEXT_COLOR));

                lblThanhTien.setText("Thành Tiền");
                lblThanhTien.setEditable(false);
                lblThanhTien.setFocusable(false);
                lblThanhTien.setBackground(AppColors.NEW_MAIN_BG_COLOR);
                lblThanhTien.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblThanhTien.setBorder(BorderFactory.createEmptyBorder(2,5,2,5));
                lblThanhTien.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lblThanhTienActionPerformed(evt);
                        }
                });

                textThanhTien.setEditable(false);
                textThanhTien.setFocusable(false);
                textThanhTien.setBackground(Color.WHITE);
                textThanhTien.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                textThanhTien.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel9Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(textThanhTien)
                                                                                .addComponent(lblThanhTien,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                288,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel9Layout.setVerticalGroup(
                                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel9Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblThanhTien,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textThanhTien,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                40, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 320, 120));

                // Action button panel container
                JPanel actionButtonPanel = new JPanel();
                actionButtonPanel.setBackground(AppColors.NEW_MAIN_BG_COLOR);
                actionButtonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 10));

                // Move "Thêm" button to the right of "Chi Phí" panel
                jButton18.setText("Thêm");
                jButton18.setBackground(AppColors.NEW_DEFAULT_BUTTON_COLOR);
                jButton18.setForeground(Color.WHITE);
                jButton18.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                jButton18.setPreferredSize(new java.awt.Dimension(120, 50));
                jButton18.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton18ActionPerformed(evt);
                    }
                });
                // Add "Thêm" button directly to jPanel7 instead of actionButtonPanel
                jPanel7.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 65, 120, 50));

                // Primary action buttons in the bottom panel
                jButton17.setText("Xác nhận");
                jButton17.setBackground(AppColors.NEW_DEFAULT_BUTTON_COLOR);
                jButton17.setForeground(Color.WHITE);
                jButton17.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                jButton17.setPreferredSize(new java.awt.Dimension(140, 40));
                jButton17.addActionListener(evt -> jButton17ActionPerformed(evt));
                actionButtonPanel.add(jButton17);

                // Move "Hủy" button to the right of "Nhà cung cấp" panel
                jButton15.setText("Hủy");
                jButton15.setBackground(AppColors.NEW_QUICK_ACCESS_BUTTON_BG_COLOR);
                jButton15.setForeground(AppColors.NEW_QUICK_ACCESS_BUTTON_TEXT_COLOR);
                jButton15.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                jButton15.setPreferredSize(new java.awt.Dimension(120, 50));
                jButton15.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        // Reset các trường nhập liệu ở phần Đặt hàng
                        cbMaSanPham.setSelectedIndex(0);
                        textTenSanPham.setText("");
                        txtMauSac.setText("");
                        txtKichThuoc.setText("");
                        textSoLuong.setText("");
                        jTextField7.setText("");
                        textThanhTien.setText("");
                        // Không reset lblThanhTien (ô mô tả)
                    }
                });
                // Add "Hủy" button directly to jPanel7 instead of actionButtonPanel
                jPanel7.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 205, 120, 50));

                // Secondary action button remaining in the bottom panel
                jButton16.setText("Xóa");
                jButton16.setBackground(AppColors.NEW_QUICK_ACCESS_BUTTON_BG_COLOR);
                jButton16.setForeground(AppColors.NEW_QUICK_ACCESS_BUTTON_TEXT_COLOR);
                jButton16.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                jButton16.setPreferredSize(new java.awt.Dimension(140, 40));
                jButton16.addActionListener(evt -> jButton16ActionPerformed(evt));
                actionButtonPanel.add(jButton16);

                // Add the action button panel to the main panel - centered and adjusted size
                // jPanel7.add(actionButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 360, 60)); // Consider if this is still needed or conflicts

                lblTongTienPhieuNhap.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 12));
                lblTongTienPhieuNhap.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                lblTongTienPhieuNhap.setText("Tổng tiền:");

                txtTongTienPhieuNhap.setEditable(false);
                txtTongTienPhieuNhap.setBackground(java.awt.Color.WHITE);
                txtTongTienPhieuNhap.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                txtTongTienPhieuNhap.setBorder(javax.swing.BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));
                txtTongTienPhieuNhap.setPreferredSize(new java.awt.Dimension(150, 40));
                txtTongTienPhieuNhap.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                txtTongTienPhieuNhap.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
                txtTongTienPhieuNhap.setText("0.00");

                javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
                pnlContent.setLayout(pnlContentLayout);
                pnlContentLayout.setHorizontalGroup(
                    pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlContentLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addContainerGap(19, Short.MAX_VALUE))
                        .addGroup(pnlContentLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(lblTongTienPhieuNhap)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTongTienPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30))
                );
                pnlContentLayout.setVerticalGroup(
                    pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlContentLayout.createSequentialGroup()
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                            .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTongTienPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTongTienPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20))
                );

                containerPanel.add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 630));

                // Khởi tạo các thành phần tìm kiếm
                cbSearchType = new javax.swing.JComboBox<>(new String[] {"Mã PN", "Mã NCC", "Mã SP", "Trạng thái"});
                cbSearchType.setBackground(Color.WHITE);
                cbSearchType.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);

                txtSearchValue = new javax.swing.JTextField();
                txtSearchValue.setBackground(Color.WHITE);
                txtSearchValue.setForeground(AppColors.NEW_MAIN_TEXT_COLOR);
                txtSearchValue.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));

                btnSearch = new javax.swing.JButton("Tìm kiếm");
                btnSearch.setBackground(AppColors.NEW_DEFAULT_BUTTON_COLOR);
                btnSearch.setForeground(Color.WHITE);
                btnSearch.setBorder(BorderFactory.createLineBorder(AppColors.NEW_BORDER_LINES_COLOR));

                // Thêm vào giao diện (ví dụ đặt trên pnlContent)
                pnlContent.add(cbSearchType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));
                pnlContent.add(txtSearchValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 200, 30));
                pnlContent.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 100, 30));
                // Thêm sự kiện cho nút tìm kiếm
                btnSearch.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        performSearch();
                    }
                });

                setupUI();
        } // </editor-fold>//GEN-END:initComponents

        private void lblThanhTienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lblThanhTienActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_lblThanhTienActionPerformed

        private void setupUI() {
                // Điều chỉnh kích thước các panel con trong pnlContent
                jPanel7.setPreferredSize(new java.awt.Dimension(960, 317));
                jScrollPane1.setPreferredSize(new java.awt.Dimension(960, 190));
        }

        private void lblNCCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lblNCCActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_lblNCCActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Validate input
            if (cbMaSanPham.getSelectedItem() == null || textSoLuong.getText().trim().isEmpty() || 
                cbMaNCC.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                return;
            }

            // Kiểm tra số lượng là số nguyên dương
            int soLuong;
            try {
                soLuong = Integer.parseInt(textSoLuong.getText().trim());
                if (soLuong <= 0) {
                    JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ!");
                    return;
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ!");
                return;
            }

            // Tạo mã phiếu nhập tiếp theo theo thứ tự
            String nextMaPN = nhapHangBUS.generateNextMaPN();
            
            // Create new import record
            nhapHangDTO nh = new nhapHangDTO();
            nh.setMaPN(nextMaPN);
            nh.setMaSanPham((String) cbMaSanPham.getSelectedItem());
            nh.setMaNhaCungCap((String) cbMaNCC.getSelectedItem());
            nh.setTenSanPham(textTenSanPham.getText());
            nh.setMauSac(txtMauSac.getText());
            nh.setKichThuoc(txtKichThuoc.getText());
            nh.setSoLuong(textSoLuong.getText());
            nh.setDonGia(jTextField7.getText());
            nh.setThanhTien(textThanhTien.getText());
            nh.setTrangThai("Đang xử lý");
            nh.setThoiGian(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date()));
            nh.setHinhThucThanhToan((String) cbHinhThucThanhToan.getSelectedItem());

            if (nhapHangBUS.themNhapHang(nh)) {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công");
                loadImportTable(); // Refresh table
                // Clear input fields
                cbMaSanPham.setSelectedIndex(0);
                cbMaNCC.setSelectedIndex(0);
                cbTenNCC.setSelectedIndex(0);
                textTenSanPham.setText("");
                txtMauSac.setText("");
                txtKichThuoc.setText("");
                textSoLuong.setText("");
                jTextField7.setText("");
                textThanhTien.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }

        private void txtKichThuocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKichThuocActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtKichThuocActionPerformed

    private void textSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSoLuongActionPerformed

        private void populateComboBoxes() {
                // Mã SP
                cbMaSanPham.removeAllItems();
                for (String code : sanPhamBUS.getAllProductCodes()) {
                    cbMaSanPham.addItem(code);
                }

        // Nhà cung cấp
        cbMaNCC.removeAllItems();
        cbTenNCC.removeAllItems();
        List<DTO.nhaCungCapDTO> nccList = nhaCungCapBUS.getAllNhaCungCap();
        for (DTO.nhaCungCapDTO ncc : nccList) {
            cbMaNCC.addItem(ncc.getMaNhaCungCap());
            cbTenNCC.addItem(ncc.getTenNhaCungCap());
        }
        cbMaNCC.addActionListener(e -> {
            int idx = cbMaNCC.getSelectedIndex();
            if (idx >= 0 && idx < cbTenNCC.getItemCount()) cbTenNCC.setSelectedIndex(idx);
        });
        cbTenNCC.addActionListener(e -> {
            int idx = cbTenNCC.getSelectedIndex();
            if (idx >= 0 && idx < cbMaNCC.getItemCount()) cbMaNCC.setSelectedIndex(idx);
        });

        // Add event listener for MaSP selection
        cbMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String selectedMaSP = (String) cbMaSanPham.getSelectedItem();
                if (selectedMaSP != null && !selectedMaSP.isEmpty()) {
                    // Lấy thông tin sản phẩm
                    sanPhamDTO sp = sanPhamBUS.getSanPhamByMa(selectedMaSP);
                    if (sp != null) {
                        textTenSanPham.setText(sp.getTenSanPham());
                        txtMauSac.setText(sp.getMauSac());
                        txtKichThuoc.setText(sp.getSize());
                        jTextField7.setText(String.valueOf(sp.getGiaBan()));
                        textSoLuong.setText("1");
                        calculateAmount();
                    }
                    // Lọc nhà cung cấp theo mã sản phẩm
                    NhaCungCapDAO nccDAO = new NhaCungCapDAO();
                    List<DTO.nhaCungCapDTO> nccList = nccDAO.getNhaCungCapByMaSanPham(selectedMaSP);
                    cbMaNCC.removeAllItems();
                    cbTenNCC.removeAllItems();
                    for (DTO.nhaCungCapDTO ncc : nccList) {
                        cbMaNCC.addItem(ncc.getMaNhaCungCap());
                        cbTenNCC.addItem(ncc.getTenNhaCungCap());
                    }
                    // Nếu không có NCC nào thì disable 2 combobox
                    boolean hasNCC = !nccList.isEmpty();
                    cbMaNCC.setEnabled(hasNCC);
                    cbTenNCC.setEnabled(hasNCC);
                    // Đồng bộ 2 combobox
                    cbMaNCC.addActionListener(e2 -> {
                        int idx = cbMaNCC.getSelectedIndex();
                        if (idx >= 0 && idx < cbTenNCC.getItemCount()) cbTenNCC.setSelectedIndex(idx);
                    });
                    cbTenNCC.addActionListener(e2 -> {
                        int idx = cbTenNCC.getSelectedIndex();
                        if (idx >= 0 && idx < cbMaNCC.getItemCount()) cbMaNCC.setSelectedIndex(idx);
                    });
                }
            }
        });
    }

    private void filterSuppliers() {
        String selectedType = (String) cbMaSanPham.getSelectedItem();
        
        if (selectedType != null) {
            NhaCungCapDAO nhaCungCapDAO = new NhaCungCapDAO();
            List<String> filteredSuppliers = nhaCungCapDAO.getSuppliersByProduct(selectedType, selectedType);
            
            cbMaNCC.removeAllItems();
            cbTenNCC.removeAllItems();
            for (String supplier : filteredSuppliers) {
                cbMaNCC.addItem(supplier);
                cbTenNCC.addItem(supplier);
            }
            if (filteredSuppliers.isEmpty()) {
                cbMaNCC.addItem("Không có nhà cung cấp phù hợp");
                cbTenNCC.addItem("Không có nhà cung cấp phù hợp");
            }
        }
    }

        private void loadImportTable() {
                List<nhapHangDTO> list = nhapHangBUS.getAllNhapHang();
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                // Đảm bảo STT bắt đầu từ 1 và tăng dần
        int stt = 1;
        for (nhapHangDTO nh : list) {
            model.addRow(new Object[]{
                stt++,
                nh.getMaPN(),
                nh.getMaNhaCungCap(),
                nh.getMaSanPham(),
                nh.getTenSanPham(),
                nh.getMauSac(),
                nh.getKichThuoc(),
                nh.getSoLuong(),
                nh.getDonGia(),
                nh.getThanhTien(),
                nh.getHinhThucThanhToan(),
                nh.getTrangThai()
            });
        }
        updateTongTienPhieuNhap(); // Call to update total
    }

    private void setupAmountCalculation() {
        javax.swing.event.DocumentListener listener = new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { calculateAmount(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { calculateAmount(); }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { calculateAmount(); }
        };
        textSoLuong.getDocument().addDocumentListener(listener); // Số lượng
        jTextField7.getDocument().addDocumentListener(listener);  // Đơn giá
    }

    private void calculateAmount() {
        try {
            int soLuong = Integer.parseInt(textSoLuong.getText());
            double donGia = Double.parseDouble(jTextField7.getText());
            double thanhTien = soLuong * donGia;
            textThanhTien.setText(String.valueOf(thanhTien));
        } catch (NumberFormatException e) {
            textThanhTien.setText("0");
        }
        updateTongTienPhieuNhap(); // Call to update total
    }

        private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
                try {
                        if (nhapHangBUS.chuyenNhapHangSangPhieuNhap()) {
                                JOptionPane.showMessageDialog(this, "Nhập hàng thành công!");
                                loadImportTable(); // Refresh lại bảng NhapHang
                        } else {
                                JOptionPane.showMessageDialog(this, "Có lỗi khi xác nhận nhập hàng");
                        }
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
                }
        }

        private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, "Vui lòng chọn một phiếu nhập để xóa!");
                        return;
                }
                String maPN = jTable1.getValueAt(selectedRow, 1).toString();
                int confirm = JOptionPane.showConfirmDialog(this, 
                    "Bạn có chắc chắn muốn xóa phiếu nhập này?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION);
            
                if (confirm == JOptionPane.YES_OPTION) {
                        if (nhapHangBUS.xoaNhapHang(maPN)) {
                                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                                loadImportTable();
                        } else {
                                JOptionPane.showMessageDialog(this, "Xóa thất bại! Có thể phiếu nhập này đã được sử dụng ở nơi khác.");
                        }
                }
        }

        private void clearInputFields() {
                cbMaSanPham.setSelectedIndex(0);
                textTenSanPham.setText("");
                txtMauSac.setText("");
                txtKichThuoc.setText("");
                textSoLuong.setText("");
                jTextField7.setText("");
                textThanhTien.setText("");
        }

        // Hàm thực hiện tìm kiếm
        private void performSearch() {
            String searchType = cbSearchType.getSelectedItem().toString();
            String keyword = txtSearchValue.getText().trim();
            String dbField = "";
            switch (searchType) {
                case "Mã PN": dbField = "MaPN"; break;
                case "Mã NCC": dbField = "MaNhaCungCap"; break;
                case "Mã SP": dbField = "MaSanPham"; break;
                case "Trạng thái": dbField = "TrangThai"; break;
                default: dbField = "MaPN";
            }
            List<nhapHangDTO> list;
            if (keyword.isEmpty()) {
                list = nhapHangBUS.getAllNhapHang();
            } else {
                list = nhapHangBUS.searchNhapHang(keyword, dbField);
            }
            // Cập nhật bảng
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            int stt = 1;
            for (nhapHangDTO nh : list) {
                model.addRow(new Object[]{
                    stt++,
                    nh.getMaPN(),
                    nh.getMaNhaCungCap(),
                    nh.getMaSanPham(),
                    nh.getTenSanPham(),
                    nh.getMauSac(),
                    nh.getKichThuoc(),
                    nh.getSoLuong(),
                    nh.getDonGia(),
                    nh.getThanhTien(),
                    nh.getHinhThucThanhToan(),
                    nh.getTrangThai()
                });
            }
            updateTongTienPhieuNhap(); // Call to update total
        }

        private void btnOpenSmartImportActionPerformed(java.awt.event.ActionEvent evt) {
            if (this.mainFrame != null) {
                screens.NhapHang.SmartImportAdvisorPanel smartImportPanel = new screens.NhapHang.SmartImportAdvisorPanel(this.mainFrame, this);
                this.mainFrame.switchPanel(smartImportPanel, this.mainFrame.getBtnNhapHang());
            } else {
                JOptionPane.showMessageDialog(this, "Không thể mở Trợ Lý Nhập Hàng từ context này (mainFrame is null).", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

        private void updateTongTienPhieuNhap() {
            double tongTien = 0;
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            int thanhTienColIndex = -1;

            for (int col = 0; col < model.getColumnCount(); col++) {
                if (model.getColumnName(col).equals("Thành tiền")) {
                    thanhTienColIndex = col;
                    break; 
                }
            }

            if (thanhTienColIndex == -1) {
                System.err.println("updateTongTienPhieuNhap: Column 'Thành tiền' not found.");
                txtTongTienPhieuNhap.setText("Error");
                return;
            }

            for (int i = 0; i < model.getRowCount(); i++) {
                Object thanhTienObj = model.getValueAt(i, thanhTienColIndex);
                if (thanhTienObj != null) {
                    try {
                        if (thanhTienObj instanceof Number) {
                            tongTien += ((Number) thanhTienObj).doubleValue();
                        } else {
                            tongTien += Double.parseDouble(thanhTienObj.toString());
                        }
                    } catch (NumberFormatException e) {
                        System.err.println("Lỗi parse double ở hàng " + i + " cột 'Thành tiền' trong Nhập Hàng: " + thanhTienObj + " Error: " + e.getMessage());
                    }
                }
            }
            java.text.DecimalFormat df = new java.text.DecimalFormat("#,##0.00"); // Standard format with comma for thousands, dot for decimal
            txtTongTienPhieuNhap.setText(df.format(tongTien));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel containerPanel;
        private javax.swing.JButton jButton15;
        private javax.swing.JButton jButton16;
        private javax.swing.JButton jButton17;
        private javax.swing.JButton jButton18;
        private javax.swing.JComboBox<String> cbMaSanPham;
        private javax.swing.JComboBox<String> cbHinhThucThanhToan;
        private javax.swing.JComboBox<String> cbMaNCC;
        private javax.swing.JComboBox<String> cbTenNCC;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel lblLoaiSanPham;
        private javax.swing.JLabel lblMaSanPham;
        private javax.swing.JLabel lblTenSanPham;
        private javax.swing.JLabel lblMauSac;
        private javax.swing.JLabel lblKichThuoc;
        private javax.swing.JLabel lblSoLuong;
        private javax.swing.JLabel lblDonGia;
        private javax.swing.JLabel lblHinhThucThanhToan;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel pnlBoxSanPhamSoLuong;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator6;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextField textTenSanPham;
        private javax.swing.JTextField textSoLuong;
        private javax.swing.JTextField lblNCC;
        private javax.swing.JTextField txtMauSac;
        private javax.swing.JTextField txtKichThuoc;
        private javax.swing.JTextField lblNhaCungCap;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField lblThanhTien;
        private javax.swing.JTextField textThanhTien;
        private javax.swing.JPanel pnlContent;
        private javax.swing.JPanel pnlHeader;
        // End of variables declaration//GEN-END:variables

        public void refreshImportTable() {
                loadImportTable();
        }
}