/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package screens.NhapHang;

import javax.swing.UIManager;
import javax.swing.JOptionPane;
import DAO.SanPhamDAO;
import DAO.PhieuNhapDAO;
import DTO.PhieuNhapDTO;
import DTO.sanPhamDTO;
import java.util.Date;
import java.util.List;
import DAO.NhaCungCapDAO;
import DAO.NhapHangDAO;
import DTO.nhapHangDTO;
import DTO.hoaDonDTO;
import BUS.HoaDonBUS;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.util.stream.Collectors;
import DAO.NhaCungCap_SanPhamDAO;
import DTO.NhaCungCap_SanPhamDTO;
import BUS.NhapHangBUS;
import BUS.SanPhamBUS;
import BUS.NhaCungCapBUS;

/**
 *
 * @author nson9
 */
public class nhaphang extends javax.swing.JPanel {

        private javax.swing.JLabel lblMaNCC;
        private javax.swing.JLabel lblTenNCC;

        private NhapHangBUS nhapHangBUS;
        private SanPhamBUS sanPhamBUS;
        private NhaCungCapBUS nhaCungCapBUS;

        /**
         * Creates new form phieunhap
         */
        public nhaphang() {
                nhapHangBUS = new NhapHangBUS();
                sanPhamBUS = new SanPhamBUS();
                nhaCungCapBUS = new NhaCungCapBUS();
                initComponents();
                populateComboBoxes();
                loadImportTable();
                setupAmountCalculation();
        }

        public javax.swing.JPanel getNhapHangPanel() {
                return containerPanel;
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                // Khởi tạo các panel chính
                containerPanel = new javax.swing.JPanel();
                containerPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
                containerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1 = new javax.swing.JPanel();
                pnlHeader = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                pnlContent = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jPanel7 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                lblNhaCungCap = new javax.swing.JTextField();
                cbMaNCC = new javax.swing.JComboBox<>();
                cbTenNCC = new javax.swing.JComboBox<>();
                lblNCC = new javax.swing.JTextField();
                pnlBoxSanPhamSoLuong = new javax.swing.JPanel();
                cbMaSanPham = new javax.swing.JComboBox<>();
                cbHinhThucThanhToan = new javax.swing.JComboBox<>();
                jTextField7 = new javax.swing.JTextField();
                lblLoaiSanPham = new javax.swing.JLabel();
                lblMaSanPham = new javax.swing.JLabel();
                lblTenSanPham = new javax.swing.JLabel();
                lblMauSac = new javax.swing.JLabel();
                lblKichThuoc = new javax.swing.JLabel();
                lblSoLuong = new javax.swing.JLabel();
                lblDonGia = new javax.swing.JLabel();
                lblHinhThucThanhToan = new javax.swing.JLabel();
                textTenSanPham = new javax.swing.JTextField();
                txtMauSac = new javax.swing.JTextField();
                txtKichThuoc = new javax.swing.JTextField();
                textSoLuong = new javax.swing.JTextField();
                jPanel9 = new javax.swing.JPanel();
                lblThanhTien = new javax.swing.JTextField();
                textThanhTien = new javax.swing.JTextField();
                jButton15 = new javax.swing.JButton();
                jButton18 = new javax.swing.JButton();
                jButton16 = new javax.swing.JButton();
                jButton17 = new javax.swing.JButton();

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 390, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 300, Short.MAX_VALUE));

                pnlHeader.setBackground(new java.awt.Color(12, 150, 156));

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                jLabel1.setText("Quản lý  nhập hàng");

                javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
                pnlHeader.setLayout(pnlHeaderLayout);
                pnlHeaderLayout.setHorizontalGroup(
                                pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                pnlHeaderLayout.createSequentialGroup()
                                                                                .addContainerGap(422, Short.MAX_VALUE)
                                                                                .addComponent(jLabel1)
                                                                                .addGap(370, 370, 370)));
                pnlHeaderLayout.setVerticalGroup(
                                pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlHeaderLayout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(14, Short.MAX_VALUE)));

                containerPanel.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

                pnlContent.setBackground(new java.awt.Color(107, 163, 190));

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null },
                                                { null, null, null, null, null, null, null, null, null, null, null,
                                                                null }
                                },
                                new String[] {
                                                "STT", "Ma PN", "Mã NCC", "Mã SP", "Tên SP", "Màu sắc",
                                                "Kích thước", "Số Lượng",
                                                "Đơn giá", "Thành tiền", "Hình thức thanh toán", "Trạng thái"
                                }));
                jTable1.setShowGrid(true);
                jScrollPane1.setViewportView(jTable1);

                jPanel7.setBackground(new java.awt.Color(107, 163, 190));
                jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Đặt hàng"));
                jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel5.setBackground(new java.awt.Color(107, 163, 190));
                jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)),
                                "Nhà cung cấp"));

                lblNhaCungCap.setText("Chọn nhà cung cấp ");

                lblMaNCC = new javax.swing.JLabel("Mã NCC");
                lblTenNCC = new javax.swing.JLabel("Tên NCC");

                cbMaNCC = new javax.swing.JComboBox<>();
                cbTenNCC = new javax.swing.JComboBox<>();

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                                                .addComponent(lblMaNCC)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(cbMaNCC, 0, 180,
                                                                                                                Short.MAX_VALUE))
                                                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                                                .addComponent(lblTenNCC)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(cbTenNCC, 0, 180,
                                                                                                                Short.MAX_VALUE)))
                                                                .addContainerGap()));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblMaNCC)
                                                                                .addComponent(cbMaNCC,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(lblTenNCC)
                                                                                .addComponent(cbTenNCC,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));

                jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 320, -1));

                pnlBoxSanPhamSoLuong.setBackground(new java.awt.Color(107, 163, 190));
                pnlBoxSanPhamSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)),
                                "Sản phẩm & Số lượng"));

                cbMaSanPham.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                lblMaSanPham.setText("Mã SP");

                lblTenSanPham.setText("Tên SP");

                lblMauSac.setText("Màu sắc");

                lblKichThuoc.setText("Kích thước");

                lblSoLuong.setText("Số lượng");

                lblDonGia.setText("Đơn giá");

                lblHinhThucThanhToan.setText("Hình thức thanh toán");

                cbHinhThucThanhToan.setModel(
                                new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Tiền mặt", "Chuyển khoản", "Thẻ" }));

                txtKichThuoc.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtKichThuocActionPerformed(evt);
                        }
                });

                textSoLuong.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textSoLuongActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout pnlBoxSanPhamSoLuongLayout = new javax.swing.GroupLayout(pnlBoxSanPhamSoLuong);
                pnlBoxSanPhamSoLuong.setLayout(pnlBoxSanPhamSoLuongLayout);
                pnlBoxSanPhamSoLuongLayout.setHorizontalGroup(
                                pnlBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(pnlBoxSanPhamSoLuongLayout
                                                                                                .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(lblMauSac)
                                                                                                .addGroup(pnlBoxSanPhamSoLuongLayout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblMaSanPham)
                                                                                                                .addComponent(lblTenSanPham))
                                                                                                .addComponent(lblDonGia))
                                                                                .addComponent(lblKichThuoc)
                                                                                .addGroup(pnlBoxSanPhamSoLuongLayout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(1, 1, 1)
                                                                                                .addComponent(lblSoLuong))
                                                                                .addComponent(lblHinhThucThanhToan))
                                                                .addGap(50, 50, 50)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(cbMaSanPham, 0, 172,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jTextField7)
                                                                                .addComponent(textTenSanPham)
                                                                                .addComponent(txtMauSac)
                                                                                .addComponent(txtKichThuoc)
                                                                                .addComponent(textSoLuong)
                                                                                .addComponent(cbHinhThucThanhToan, 0,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap(22, Short.MAX_VALUE)));
                pnlBoxSanPhamSoLuongLayout.setVerticalGroup(
                                pnlBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(cbMaSanPham,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblMaSanPham))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(textTenSanPham,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblTenSanPham))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtMauSac,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblMauSac))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(txtKichThuoc,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblKichThuoc))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                18,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(textSoLuong,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblSoLuong))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jTextField7,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblDonGia))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(pnlBoxSanPhamSoLuongLayout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(cbHinhThucThanhToan,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(lblHinhThucThanhToan))
                                                                .addGap(9, 9, 9)));

                jPanel7.add(pnlBoxSanPhamSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 36, -1, 270));

                jPanel9.setBackground(new java.awt.Color(107, 163, 190));
                jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(
                                javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chi phí"));

                lblThanhTien.setText("Thành tiền");
                lblThanhTien.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                lblThanhTienActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
                jPanel9.setLayout(jPanel9Layout);
                jPanel9Layout.setHorizontalGroup(
                                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(jPanel9Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(textThanhTien)
                                                                                .addComponent(lblThanhTien,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                288,
                                                                                                Short.MAX_VALUE))
                                                                .addContainerGap()));
                jPanel9Layout.setVerticalGroup(
                                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel9Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblThanhTien,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                42,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(textThanhTien,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                40, Short.MAX_VALUE)
                                                                .addContainerGap()));

                jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 310, -1));

        jButton15.setText("Hủy");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Reset các trường nhập liệu ở phần Đặt hàng
                cbMaSanPham.setSelectedIndex(0);
                textTenSanPham.setText("");
                txtMauSac.setText("");
                txtKichThuoc.setText("");
                textSoLuong.setText("");
                jTextField7.setText("");
                textThanhTien.setText("");
                // Không reset lblThanhTien (ô mô tả)
            }
        });
        jPanel7.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, -1, 60));

                jButton18.setText("Thêm");
                jButton18.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton18ActionPerformed(evt);
                        }
                });
                jPanel7.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, 64));

                jButton16.setText("Xóa");
                jButton16.addActionListener(evt -> jButton16ActionPerformed(evt));
                jPanel7.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, 60));

                jButton17.setText("Xác nhận và Xuất Phiếu Nhập ");
                jButton17.addActionListener(evt -> jButton17ActionPerformed(evt));
                jPanel7.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, 60));

                javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
                pnlContent.setLayout(pnlContentLayout);
                pnlContentLayout.setHorizontalGroup(
                                pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton16,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                164,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(100, 100, 100)
                                                                .addComponent(jButton17,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                205,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(229, 229, 229))
                                                .addGroup(pnlContentLayout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addGroup(pnlContentLayout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addComponent(jPanel7,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                961,
                                                                                                Short.MAX_VALUE)
                                                                                .addComponent(jScrollPane1))
                                                                .addContainerGap(19, Short.MAX_VALUE)));
                pnlContentLayout.setVerticalGroup(
                                pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlContentLayout.createSequentialGroup()
                                                                .addComponent(jPanel7,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                340,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                192,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                26,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(
                                                                                pnlContentLayout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jButton16,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                46,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jButton17,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                46,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(20, 20, 20)));

                containerPanel.add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 630));

                setupUI();
        } // </editor-fold>//GEN-END:initComponents

        private void lblThanhTienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lblThanhTienActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_lblThanhTienActionPerformed

        private void setupUI() {
                // Điều chỉnh kích thước các panel con trong pnlContent
                jPanel7.setPreferredSize(new java.awt.Dimension(960, 317));
                jScrollPane1.setPreferredSize(new java.awt.Dimension(960, 190));
        }

        private void lblNCCActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_lblNCCActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_lblNCCActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Validate input
            if (cbMaSanPham.getSelectedItem() == null || textSoLuong.getText().trim().isEmpty() || 
                jComboBox9.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
                return;
            }

            // Create new import record
            nhapHangDTO nh = new nhapHangDTO();
            nh.setMaPN("PN" + System.currentTimeMillis());
            nh.setMaSanPham((String) cbMaSanPham.getSelectedItem());
            nh.setMaNhaCungCap((String) cbMaNCC.getSelectedItem());
            nh.setTenSanPham(textTenSanPham.getText());
            nh.setMauSac(txtMauSac.getText());
            nh.setKichThuoc(txtKichThuoc.getText());
            nh.setSoLuong(textSoLuong.getText());
            nh.setDonGia(jTextField7.getText());
            nh.setThanhTien(textThanhTien.getText());
            nh.setTrangThai("Đang xử lý");
            nh.setThoiGian(new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date()));
            nh.setHinhThucThanhToan((String) cbHinhThucThanhToan.getSelectedItem());

            if (nhapHangBUS.themNhapHang(nh)) {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công!");
                loadImportTable(); // Refresh table
                // Clear input fields
                cbMaSanPham.setSelectedIndex(0);
                cbMaNCC.setSelectedIndex(0);
                cbTenNCC.setSelectedIndex(0);
                textTenSanPham.setText("");
                txtMauSac.setText("");
                txtKichThuoc.setText("");
                textSoLuong.setText("");
                jTextField7.setText("");
                textThanhTien.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thất bại!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
        }
    }

        private void txtKichThuocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtKichThuocActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtKichThuocActionPerformed

    private void textSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSoLuongActionPerformed

        private void populateComboBoxes() {
                // Mã SP
                cbMaSanPham.removeAllItems();
                for (String code : sanPhamBUS.getAllProductCodes()) {
                    cbMaSanPham.addItem(code);
                }

        // Nhà cung cấp
        cbMaNCC.removeAllItems();
        cbTenNCC.removeAllItems();
        List<DTO.nhaCungCapDTO> nccList = nhaCungCapDAO.getAllNhaCungCap();
        for (DTO.nhaCungCapDTO ncc : nccList) {
            cbMaNCC.addItem(ncc.getMaNhaCungCap());
            cbTenNCC.addItem(ncc.getTenNhaCungCap());
        }
        cbMaNCC.addActionListener(e -> {
            int idx = cbMaNCC.getSelectedIndex();
            if (idx >= 0 && idx < cbTenNCC.getItemCount()) cbTenNCC.setSelectedIndex(idx);
        });
        cbTenNCC.addActionListener(e -> {
            int idx = cbTenNCC.getSelectedIndex();
            if (idx >= 0 && idx < cbMaNCC.getItemCount()) cbMaNCC.setSelectedIndex(idx);
        });

        // Add event listener for MaSP selection
        cbMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String selectedMaSP = (String) cbMaSanPham.getSelectedItem();
                if (selectedMaSP != null && !selectedMaSP.isEmpty()) {
                    // Lấy thông tin sản phẩm
                    sanPhamDTO sp = sanPhamDAO.getSanPhamByMa(selectedMaSP);
                    if (sp != null) {
                        textTenSanPham.setText(sp.getTenSanPham());
                        txtMauSac.setText(sp.getMauSac());
                        txtKichThuoc.setText(sp.getSize());
                        jTextField7.setText(String.valueOf(sp.getGiaBan()));
                        textSoLuong.setText("1");
                        calculateAmount();
                    }
                    // Lọc nhà cung cấp theo mã sản phẩm
                    NhaCungCapDAO nccDAO = new NhaCungCapDAO();
                    List<DTO.nhaCungCapDTO> nccList = nccDAO.getNhaCungCapByMaSanPham(selectedMaSP);
                    cbMaNCC.removeAllItems();
                    cbTenNCC.removeAllItems();
                    for (DTO.nhaCungCapDTO ncc : nccList) {
                        cbMaNCC.addItem(ncc.getMaNhaCungCap());
                        cbTenNCC.addItem(ncc.getTenNhaCungCap());
                    }
                    // Nếu không có NCC nào thì disable 2 combobox
                    boolean hasNCC = !nccList.isEmpty();
                    cbMaNCC.setEnabled(hasNCC);
                    cbTenNCC.setEnabled(hasNCC);
                    // Đồng bộ 2 combobox
                    cbMaNCC.addActionListener(e2 -> {
                        int idx = cbMaNCC.getSelectedIndex();
                        if (idx >= 0 && idx < cbTenNCC.getItemCount()) cbTenNCC.setSelectedIndex(idx);
                    });
                    cbTenNCC.addActionListener(e2 -> {
                        int idx = cbTenNCC.getSelectedIndex();
                        if (idx >= 0 && idx < cbMaNCC.getItemCount()) cbMaNCC.setSelectedIndex(idx);
                    });
                }
            }
        });
    }

    private void filterSuppliers() {
        String selectedType = (String) cbMaSanPham.getSelectedItem();
        
        if (selectedType != null) {
            NhaCungCapDAO nhaCungCapDAO = new NhaCungCapDAO();
            List<String> filteredSuppliers = nhaCungCapDAO.getSuppliersByProduct(selectedType, selectedType);
            
            cbMaNCC.removeAllItems();
            cbTenNCC.removeAllItems();
            for (String supplier : filteredSuppliers) {
                cbMaNCC.addItem(supplier);
                cbTenNCC.addItem(supplier);
            }
            if (filteredSuppliers.isEmpty()) {
                cbMaNCC.addItem("Không có nhà cung cấp phù hợp");
                cbTenNCC.addItem("Không có nhà cung cấp phù hợp");
            }
        }
    }

        private void loadImportTable() {
                List<nhapHangDTO> list = nhapHangBUS.getAllNhapHang();
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

        int stt = 1;
        for (nhapHangDTO nh : list) {
            model.addRow(new Object[]{
                stt++,
                nh.getMaPN(),
                nh.getMaNhaCungCap(),
                nh.getMaSanPham(),
                nh.getTenSanPham(),
                nh.getMauSac(),
                nh.getKichThuoc(),
                nh.getSoLuong(),
                nh.getDonGia(),
                nh.getThanhTien(),
                nh.getHinhThucThanhToan(),
                nh.getTrangThai()
            });
        }
    }

    private void setupAmountCalculation() {
        javax.swing.event.DocumentListener listener = new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) { calculateAmount(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { calculateAmount(); }
            public void insertUpdate(javax.swing.event.DocumentEvent e) { calculateAmount(); }
        };
        textSoLuong.getDocument().addDocumentListener(listener); // Số lượng
        jTextField7.getDocument().addDocumentListener(listener);  // Đơn giá
    }

    private void calculateAmount() {
        try {
            int soLuong = Integer.parseInt(textSoLuong.getText());
            double donGia = Double.parseDouble(jTextField7.getText());
            double thanhTien = soLuong * donGia;
            textThanhTien.setText(String.valueOf(thanhTien));
        } catch (NumberFormatException e) {
            textThanhTien.setText("0");
        }
    }

        private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
                try {
                        if (nhapHangBUS.xuLyPhieuNhap()) {
                                JOptionPane.showMessageDialog(this, "Xử lý phiếu nhập thành công!");
                                loadImportTable();
                        } else {
                                JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi xử lý phiếu nhập!");
                        }
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Lỗi: " + e.getMessage());
                }
        }

        private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow == -1) {
                        JOptionPane.showMessageDialog(this, "Vui lòng chọn một phiếu nhập để xóa!");
                        return;
                }
                String maPN = jTable1.getValueAt(selectedRow, 1).toString();
                int confirm = JOptionPane.showConfirmDialog(this, 
                    "Bạn có chắc chắn muốn xóa phiếu nhập này?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION);
            
                if (confirm == JOptionPane.YES_OPTION) {
                        if (nhapHangBUS.xoaNhapHang(maPN)) {
                                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                                loadImportTable();
                        } else {
                                JOptionPane.showMessageDialog(this, "Xóa thất bại! Có thể phiếu nhập này đã được sử dụng ở nơi khác.");
                        }
                }
        }

        private void clearInputFields() {
                cbMaSanPham.setSelectedIndex(0);
                textTenSanPham.setText("");
                txtMauSac.setText("");
                txtKichThuoc.setText("");
                textSoLuong.setText("");
                jTextField7.setText("");
                textThanhTien.setText("");
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(nhaphang.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(nhaphang.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(nhaphang.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(nhaphang.class.getName()).log(java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new nhaphang().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel containerPanel;
        private javax.swing.JButton jButton15;
        private javax.swing.JButton jButton16;
        private javax.swing.JButton jButton17;
        private javax.swing.JButton jButton18;
        private javax.swing.JComboBox<String> cbMaSanPham;
        private javax.swing.JComboBox<String> cbHinhThucThanhToan;
        private javax.swing.JComboBox<String> cbMaNCC;
        private javax.swing.JComboBox<String> cbTenNCC;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel lblLoaiSanPham;
        private javax.swing.JLabel lblMaSanPham;
        private javax.swing.JLabel lblTenSanPham;
        private javax.swing.JLabel lblMauSac;
        private javax.swing.JLabel lblKichThuoc;
        private javax.swing.JLabel lblSoLuong;
        private javax.swing.JLabel lblDonGia;
        private javax.swing.JLabel lblHinhThucThanhToan;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JPanel pnlBoxSanPhamSoLuong;
        private javax.swing.JPanel jPanel9;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator6;
        private javax.swing.JTable jTable1;
        private javax.swing.JTextField textTenSanPham;
        private javax.swing.JTextField textSoLuong;
        private javax.swing.JTextField lblNCC;
        private javax.swing.JTextField txtMauSac;
        private javax.swing.JTextField txtKichThuoc;
        private javax.swing.JTextField lblNhaCungCap;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTextField lblThanhTien;
        private javax.swing.JTextField textThanhTien;
        private javax.swing.JPanel pnlContent;
        private javax.swing.JPanel pnlHeader;
        // End of variables declaration//GEN-END:variables
}