package screens.XuatHang;

import javax.swing.UIManager;
import javax.swing.JOptionPane;
import DAO.SanPhamDAO;
import java.util.List;

/**
 *
 * @author nson9
 */
public class xuathang extends javax.swing.JPanel {

    /**
     * Creates new form hoadon
     */
    public xuathang() {
        initComponents();
        loadComboBoxData();
        loadXuatHangTable();
        javax.swing.event.DocumentListener docListener = new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { calculateThanhTien(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { calculateThanhTien(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { calculateThanhTien(); }
        };
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow == -1) {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần xóa!");
                    return;
                }
                // Lấy mã phiếu xuất (MaPX) từ dòng được chọn
                String maPX = jTable1.getValueAt(selectedRow, 0).toString();
                int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa phiếu xuất này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        java.sql.Connection conn = DTB.ConnectDB.getConnection();
                        String sql = "DELETE FROM XuatHang WHERE MaPX = ?";
                        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                        ps.setString(1, maPX);
                        int result = ps.executeUpdate();
                        ps.close();
                        conn.close();
                        if (result > 0) {
                            JOptionPane.showMessageDialog(null, "Xóa phiếu xuất thành công!");
                            loadXuatHangTable();
                        } else {
                            JOptionPane.showMessageDialog(null, "Xóa phiếu xuất thất bại!");
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Lỗi khi xóa phiếu xuất: " + e.getMessage());
                    }
                }
            }
        });
        jTextField10.getDocument().addDocumentListener(docListener);
        jTextField7.getDocument().addDocumentListener(docListener);
        cbMaSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String maSP = (String) cbMaSanPham.getSelectedItem();
                if (maSP != null) {
                    DAO.SanPhamDAO dao = new DAO.SanPhamDAO();
                    DTO.sanPhamDTO sp = dao.getSanPhamByMa(maSP);
                    if (sp != null) {
                        jTextField7.setText(String.valueOf(sp.getGiaBan()));
                    } else {
                        jTextField7.setText("");
                    }
                }
            }
        });
    }
    public javax.swing.JPanel getXuatHangPanel() {
        return containerPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        containerPanel = new javax.swing.JPanel();
        containerPanel.setPreferredSize(new java.awt.Dimension(1000, 700));
        containerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        pblBoxSanPhamSoLuong = new javax.swing.JPanel();
        cbMaSanPham = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        lblMaSanPham = new javax.swing.JLabel();
        lblTenSanPham = new javax.swing.JLabel();
        lblMauSac = new javax.swing.JLabel();
        lblKichThuoc = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblDonGia = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblHinhThucThanhToan = new javax.swing.JLabel();
        cbHinhThucThanhToan = new javax.swing.JComboBox<>();
        

        pnlHeader.setBackground(new java.awt.Color(12, 150, 156));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Quản lý xuất hàng");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(391, 391, 391))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        containerPanel.add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        pnlContent.setBackground(new java.awt.Color(107, 163, 190));

        jButton17.setText("Xác nhận và Xuất hóa đơn ");

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Mã PX", "Mã KH", "Tên KH", "Mã SP", "Tên SP", "Kích thước", "Màu sắc", "Số lượng", "Đơn giá", "Thành tiền", "Hình thức thanh toán", "Trạng thái"
            }
        ));
        jTable1.setShowGrid(true);
        jScrollPane1.setViewportView(jTable1);

        jPanel7.setBackground(new java.awt.Color(107, 163, 190));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Xuất hàng"));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(107, 163, 190));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Khách hàng"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setText("Mã khách hàng");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 97, 41));

        jTextField2.setText("Tên khách hàng");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 71, -1, 41));
        jPanel5.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 24, 183, 41));
        jPanel5.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 71, 183, 41));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 320, 120));

        jPanel9.setBackground(new java.awt.Color(107, 163, 190));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chi phí"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField8.setText("Thành tiền");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 288, 42));
        jPanel9.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 72, 288, 40));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 36, 310, 120));

        jButton15.setText("Hủy");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // Reset các trường nhập liệu ở phần Xuất hàng
                cbMaSanPham.setSelectedIndex(0);
                jTextField1.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField10.setText("");
                jTextField7.setText("");
                jTextField9.setText(""); // Chỉ reset ô tính tiền
                jTextField14.setText("");
                jTextField15.setText("");
                // Không reset jTextField8 (ô mô tả)
            }
        });
        jPanel7.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 72, -1, 60));

        jButton18.setText("Thêm");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    // Get data from form
                    String maPX = "PX" + System.currentTimeMillis(); // Or use your own ID generation logic
                    String maKH = jTextField14.getText().trim();
                    String tenKH = jTextField15.getText().trim();
                    String maSP = (String) cbMaSanPham.getSelectedItem();
                    String tenSP = jTextField1.getText().trim();
                    String kichThuoc = jTextField4.getText().trim();
                    String mauSac = jTextField3.getText().trim();
                    int soLuong = Integer.parseInt(jTextField10.getText().trim());
                    double donGia = Double.parseDouble(jTextField7.getText().trim());
                    double thanhTien = Double.parseDouble(jTextField9.getText().trim());
                    String trangThai = "Hoàn thành"; // Or get from a combo box if you have one
        
                    // Insert into database
                    java.sql.Connection conn = DTB.ConnectDB.getConnection();
                    String sql = "INSERT INTO XuatHang (MaPX, MaKhachHang, HoTen, MaSanPham, TenSanPham, KichThuoc, MauSac, SoLuong, DonGia, ThanhTien, TrangThai) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
                    java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, maPX);
                    ps.setString(2, maKH);
                    ps.setString(3, tenKH);
                    ps.setString(4, maSP);
                    ps.setString(5, tenSP);
                    ps.setString(6, kichThuoc);
                    ps.setString(7, mauSac);
                    ps.setInt(8, soLuong);
                    ps.setDouble(9, donGia);
                    ps.setDouble(10, thanhTien);
                    ps.setString(11, trangThai);
        
                    int result = ps.executeUpdate();
                    ps.close();
                    conn.close();
        
                    if (result > 0) {
                        JOptionPane.showMessageDialog(null, "Thêm phiếu xuất hàng thành công!");
                        loadXuatHangTable(); // Refresh table
                    } else {
                        JOptionPane.showMessageDialog(null, "Thêm phiếu xuất hàng thất bại!");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Lỗi khi thêm phiếu xuất hàng: " + e.getMessage());
                }
            }
        });
        jPanel7.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 213, -1, 64));

        pblBoxSanPhamSoLuong.setBackground(new java.awt.Color(107, 163, 190));
        pblBoxSanPhamSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sản phẩm & Số lượng"));

        cbMaSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblMaSanPham.setText("Mã SP");

        lblTenSanPham.setText("Tên SP");

        lblMauSac.setText("Màu sắc");

        lblKichThuoc.setText("Kích thước");

        lblSoLuong.setText("Số lượng");

        lblDonGia.setText("Đơn giá");

        lblHinhThucThanhToan.setText("Hình thức thanh toán");

        cbHinhThucThanhToan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tiền mặt", "Chuyển khoản", "Thẻ" }));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pblBoxSanPhamSoLuongLayout = new javax.swing.GroupLayout(pblBoxSanPhamSoLuong);
        pblBoxSanPhamSoLuong.setLayout(pblBoxSanPhamSoLuongLayout);
        pblBoxSanPhamSoLuongLayout.setHorizontalGroup(
            pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblBoxSanPhamSoLuongLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMauSac)
                        .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaSanPham)
                            .addComponent(lblTenSanPham))
                        .addComponent(lblDonGia))
                    .addComponent(lblKichThuoc)
                    .addGroup(pblBoxSanPhamSoLuongLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSoLuong))
                    .addComponent(lblHinhThucThanhToan))
                .addGap(50, 50, 50)
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbMaSanPham, 0, 172, Short.MAX_VALUE)
                    .addComponent(jTextField7)
                    .addComponent(jTextField1)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4)
                    .addComponent(jTextField10)
                    .addComponent(cbHinhThucThanhToan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pblBoxSanPhamSoLuongLayout.setVerticalGroup(
            pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pblBoxSanPhamSoLuongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaSanPham))
                .addGap(18, 18, 18)
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenSanPham))
                .addGap(18, 18, 18)
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMauSac))
                .addGap(18, 18, 18)
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKichThuoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDonGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pblBoxSanPhamSoLuongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHinhThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHinhThucThanhToan))
                .addGap(9, 9, 9))
        );

        jPanel7.add(pblBoxSanPhamSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 36, -1, 270));

        jButton1.setText("Xóa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                int selectedRow = jTable1.getSelectedRow();
                if (selectedRow == -1) {
                    JOptionPane.showMessageDialog(null, "Vui lòng chọn dòng cần xóa!");
                    return;
                }
                // Lấy mã phiếu xuất (MaPX) từ dòng được chọn
                String maPX = jTable1.getValueAt(selectedRow, 0).toString();
                int confirm = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa phiếu xuất này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    try {
                        java.sql.Connection conn = DTB.ConnectDB.getConnection();
                        String sql = "DELETE FROM XuatHang WHERE MaPX = ?";
                        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
                        ps.setString(1, maPX);
                        int result = ps.executeUpdate();
                        ps.close();
                        conn.close();
                        if (result > 0) {
                            JOptionPane.showMessageDialog(null, "Xóa phiếu xuất thành công!");
                            loadXuatHangTable();
                        } else {
                            JOptionPane.showMessageDialog(null, "Xóa phiếu xuất thất bại!");
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Lỗi khi xóa phiếu xuất: " + e.getMessage());
                    }
                }
            }
        });

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229))
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        containerPanel.add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 630));

        // Update panel positions and sizes
        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 320, -1));
        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 310, -1));
        jPanel7.add(pblBoxSanPhamSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 36, -1, 270));
        jPanel7.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, -1, 60));
        jPanel7.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, -1, 64));
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, 60));
        jPanel7.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, 60));

        // Update panel sizes
        jPanel7.setPreferredSize(new java.awt.Dimension(960, 340));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(960, 192));

        // Gọi setupUI() sau khi khởi tạo các components
        setupUI();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String maSP = cbMaSanPham.getSelectedItem().toString();
            int soLuongXuat = Integer.parseInt(jTextField10.getText());

            SanPhamDAO sanPhamDAO = new SanPhamDAO();

            // Bắt buộc kiểm tra tồn kho trước khi xuất
            if (sanPhamDAO.kiemTraTonKho(maSP, soLuongXuat)) {
                // Nếu đủ hàng, giảm tồn kho
                boolean result = sanPhamDAO.giamSoLuongTonKho(maSP, soLuongXuat);
                
                if (result) {
                    // Kiểm tra cảnh báo tồn kho thấp sau khi xuất thành công
                    boolean canhBao = sanPhamDAO.kiemTraCanhBaoTonKho(maSP);
                    if (canhBao) {
                        JOptionPane.showMessageDialog(this, "Cảnh báo: Sản phẩm sắp hết hàng, hãy nhập thêm!");
                    } else {
                        JOptionPane.showMessageDialog(this, "Xuất hàng thành công, tồn kho đã cập nhật.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Xuất hàng thất bại, lỗi cập nhật tồn kho.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không đủ tồn kho để xuất.");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng hợp lệ.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra: " + e.getMessage());
        }
    }

    private void setupUI() {
        // Điều chỉnh kích thước các panel con trong pnlContent
        jPanel7.setPreferredSize(new java.awt.Dimension(960, 317));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(960, 190));
    }

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void loadComboBoxData() {
        SanPhamDAO sanPhamDAO = new SanPhamDAO();

        // Load product codes
        List<String> codes = sanPhamDAO.getAllProductCodes();
        cbMaSanPham.removeAllItems();
        for (String code : codes) {
            cbMaSanPham.addItem(code);
        }
    }

    private void calculateThanhTien() {
        try {
            int soLuong = Integer.parseInt(jTextField10.getText().trim());
            double donGia = Double.parseDouble(jTextField7.getText().trim());
            double thanhTien = soLuong * donGia;
            jTextField9.setText(String.valueOf(thanhTien));
        } catch (NumberFormatException e) {
            jTextField9.setText(""); // Clear if input is invalid
        }
    }

    private void loadXuatHangTable() {
        try {
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            java.sql.Connection conn = DTB.ConnectDB.getConnection();
            String sql = "SELECT * FROM XuatHang";
            java.sql.PreparedStatement ps = conn.prepareStatement(sql);
            java.sql.ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                Object[] row = new Object[] {
                    rs.getString("MaPX"),
                    rs.getString("MaKhachHang"),
                    rs.getString("HoTen"),
                    rs.getString("MaSanPham"),
                    rs.getString("TenSanPham"),
                    rs.getString("KichThuoc"),
                    rs.getString("MauSac"),
                    rs.getInt("SoLuong"),
                    rs.getDouble("DonGia"),
                    rs.getDouble("ThanhTien"),
                    rs.getString("HinhThucThanhToan"),
                    rs.getString("TrangThai")
                };
                model.addRow(row);
            }

            rs.close();
            ps.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi tải dữ liệu xuất hàng: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xuathang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xuathang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xuathang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xuathang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xuathang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JComboBox<String> cbMaSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMaSanPham;
    private javax.swing.JLabel lblTenSanPham;
    private javax.swing.JLabel lblMauSac;
    private javax.swing.JLabel lblKichThuoc;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel pblBoxSanPhamSoLuong;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JLabel lblHinhThucThanhToan;
    private javax.swing.JComboBox<String> cbHinhThucThanhToan;
    // End of variables declaration//GEN-END:variables
}